name: nuxt-laravel
recipe: laravel
config:
  php: '8.2'
  webroot: backend/public
  via: nginx
  database: mysql:8.0
  xdebug: false

services:
  node:
    type: node:18
    port: 80
    build:
      - cd /app/client && npm install
    command: cd /app/client && npm run dev -- --host 0.0.0.0 --port 80

proxy:
  node:
    - nuxt-laravel.lndo.site
  appserver:
    - api.nuxt-laravel.lndo.site

tooling:
  nuxt:
    service: node
    cmd: cd /app/client && npm run dev -- --host 0.0.0.0 --port 80

  npm:
    service: node
    cmd: cd /app/client && npm