name: nuxt-laravel
recipe: laravel
config:
  php: '8.3'
  webroot: public
  via: nginx
  database: mysql:8.0

services:
  appserver:
    type: php:8.2
    ssl: true
    cert: /Users/leopoldomedeiros/.lando/certs/appserver.jobs2.crt
    key: /Users/leopoldomedeiros/.lando/certs/appserver.jobs2.key

  node:
    type: node:18
    ssl: false
    healthcheck: false

tooling:
  install:
    service: appserver
    cmd:
      - composer install --no-cache
      - php -r "file_exists('.env') || copy('.env.example', '.env');"
      - php artisan key:generate
      - php artisan migrate --seed
      - npm install
      - php artisan storage:link

  setup:
    service: appserver
    cmd:
      - composer install --no-cache
      - php -r "file_exists('.env') || copy('.env.example', '.env');"
      - php artisan key:generate
      - php artisan migrate --seed
      - npm install
      - php artisan storage:link

  tinker:
    service: appserver
    cmd: php artisan tinker

  migrate:
    service: appserver
    cmd: php artisan migrate

  rollback:
    service: appserver
    cmd: php artisan migrate:rollback --step=1
