name: nuxt-laravel
recipe: compose
# Disable the Laravel recipe and use compose instead
services:
  node:
    type: node:18
    ssl: false
    healthcheck: false
    port: 3000
    build:
      - cd /app/client && npm install
    command: cd /app/client && npm run dev -- --host 0.0.0.0 --port 3000

proxy:
  node:
    - nuxt-laravel.lndo.site:3000
    - localhost:3000

tooling:
  nuxt:
    service: node
    cmd: cd /app/client && npm run dev -- --host 0.0.0.0 --port 3000
    
  npm:
    service: node
    cmd: cd /app/client && npm